# Generated by Django 5.1.4 on 2024-12-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default=0)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Contact', models.IntegerField(default=0)),
                ('Email', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
